# victim constants
SEND_URL = "/home"
KEY_URL = "/login"
INTERVAL_SEND = 10
SERVER_IP = "localhost"
SERVER_PORT = 8000
EXCHANGE_MSG_MAX = 3
USE_POST = True
# server constants
SERVER_IP = "localhost"
SERVER_PORT = 8000